create table country(
id serial primary key,
ETL_Dt timestamp not null default now(),
Data_Ym timestamp ,
M1B real,
F_Ins_Dp real,
F_Ins_Ln real,
C_Ins_Dp real,
C_INs_Ln real,
Country_SME real,
Country_C_CL real,
Country_CL real,
MF_Bal real,
Bund_Txn_Amt real,
Stock_Index real,
WPI real,
CPI real,
Exchange_Rate real,
Rediscount_Rate real,
B_Ins_Rate real,
GDP real,
Y_DP real,
CONSTRAINT country_pkey PRIMARY KEY (id),
CONSTRAINT data_ym_idx UNIQUE(Data_Ym)
);

